import React from 'react';
import Button from './Button';
import { TestProcedure, Adulterant, FoodItem } from '../types';
import { 
  AlertTriangle, 
  CheckCircle2, 
  Beaker, 
  Eye, 
  ShieldAlert, 
  BookOpen, 
  Share2,
  Download,
  Heart
} from 'lucide-react';
import { jsPDF } from "jspdf";
import { APP_LOGO } from '../constants';

interface TestDetailsScreenProps {
  activeTest: TestProcedure | null;
  selectedFood: FoodItem | null;
  selectedAdulterant: Adulterant | null;
  isFavorite: boolean;
  onToggleFavorite: () => void;
}

export const TestDetailsScreen: React.FC<TestDetailsScreenProps> = ({ 
  activeTest, 
  selectedFood, 
  selectedAdulterant, 
  isFavorite, 
  onToggleFavorite
}) => {

  const handleShare = async () => {
    if (!activeTest || !selectedFood) return;
    
    const text = `🔬 Food Adulteration Test\n\nChecking: ${selectedFood.name}\nSuspect: ${selectedAdulterant?.name}\n\nAim: ${activeTest.aim}\nResult: ${activeTest.conclusion}\n\nGet the app to learn more!`;
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'PMIC Adulteration Test',
          text: text,
        });
      } catch (error) {
        console.log('Error sharing', error);
      }
    } else {
      navigator.clipboard.writeText(text);
      alert('Test details copied to clipboard!');
    }
  };

  const handleDownloadPDF = async () => {
    if (!activeTest || !selectedFood || !selectedAdulterant) return;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxLineWidth = pageWidth - margin * 2;
    let y = 20;

    const addLogoToPdf = async (): Promise<void> => {
        try {
            const img = new Image();
            img.crossOrigin = "Anonymous";
            img.src = APP_LOGO;
            await new Promise((resolve, reject) => {
                img.onload = resolve;
                img.onerror = reject;
            });
            const logoSize = 24;
            doc.addImage(img, 'PNG', pageWidth/2 - (logoSize/2), y, logoSize, logoSize);
            y += logoSize + 10;
        } catch (e) {
            console.warn("Could not add logo to PDF due to CORS or load error.", e);
        }
    };

    await addLogoToPdf();

    const checkPageBreak = (heightNeeded: number) => {
      if (y + heightNeeded > doc.internal.pageSize.getHeight() - margin) {
        doc.addPage();
        y = 20;
      }
    };

    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(22, 163, 74);
    doc.text("PMIC Adulteration Test", pageWidth / 2, y, { align: "center" });
    y += 10;

    doc.setFontSize(16);
    doc.setTextColor(30, 41, 59);
    doc.text(`Detecting ${selectedAdulterant.name} in ${selectedFood.name}`, pageWidth / 2, y, { align: "center" });
    y += 15;
    
    doc.setLineWidth(0.5);
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, y, pageWidth - margin, y);
    y += 10;

    const renderSection = (title: string, body: string | string[], color: [number, number, number] = [0, 0, 0], isNumbered: boolean = false) => {
       doc.setFont("helvetica", "bold");
       doc.setFontSize(12);
       doc.setTextColor(...color);
       
       checkPageBreak(15);
       doc.text(title.toUpperCase(), margin, y);
       y += 7;

       doc.setFont("helvetica", "normal");
       doc.setFontSize(11);
       doc.setTextColor(51, 65, 85);

       const lineHeight = 6;
       
       if (Array.isArray(body)) {
          body.forEach((item, index) => {
             const prefix = isNumbered ? `${index + 1}. ` : `• `;
             const lines = doc.splitTextToSize(`${prefix}${item}`, maxLineWidth);
             checkPageBreak(lines.length * lineHeight + 2);
             doc.text(lines, margin, y);
             y += lines.length * lineHeight + 2;
          });
       } else {
          const lines = doc.splitTextToSize(body, maxLineWidth);
          checkPageBreak(lines.length * lineHeight);
          doc.text(lines, margin, y);
          y += lines.length * lineHeight;
       }
       y += 8;
    };

    renderSection("Aim / Object", activeTest.aim, [21, 128, 61]);
    renderSection("Materials Required", activeTest.materials, [14, 165, 233]);
    renderSection("Procedure", activeTest.procedure, [147, 51, 234], true);
    renderSection("Observation", activeTest.observation, [29, 78, 216]);
    renderSection("Conclusion", activeTest.conclusion, [21, 128, 61]);
    renderSection("Precautions", activeTest.precautions, [180, 83, 9]);

    y += 5;
    checkPageBreak(20);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by PMIC Adulteration Checker app.", pageWidth / 2, y, { align: "center" });
    doc.text("Pioneer Montessori Inter College", pageWidth / 2, y + 5, { align: "center" });

    doc.save(`PMIC_Test_${selectedFood.name.replace(/\s+/g, '_')}.pdf`);
  };

  if (!activeTest) {
    return (
      <div className="px-6 py-10 max-w-2xl mx-auto text-center animate-fade-in">
        <div className="w-20 h-20 bg-amber-100 rounded-full flex items-center justify-center mx-auto mb-6">
          <AlertTriangle size={40} className="text-amber-600" />
        </div>
        <h2 className="text-2xl font-bold text-slate-800 mb-3">Test Not Found</h2>
        <p className="text-slate-600 mb-8">
          We don't have a verified test in our database for detecting 
          <span className="font-semibold"> {selectedAdulterant?.name}</span> in 
          <span className="font-semibold"> {selectedFood?.name}</span>.
        </p>

        <div className="bg-amber-50 p-4 rounded-xl border border-amber-200 text-amber-800 text-sm mb-8 text-left">
           <strong>Safety Notice:</strong> Please consult official FSSAI (DART) guidelines for this specific test.
        </div>
      </div>
    );
  }

  return (
    <div className="px-4 py-6 max-w-2xl mx-auto pb-20 animate-fade-in">
      <div className="mb-6 flex justify-between items-start">
        <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 bg-primary-50 text-primary-700 text-sm font-medium rounded-full mb-2">
                Experiment
            </div>
            <h2 className="text-2xl font-bold text-slate-800 leading-snug pr-4">
                Detecting {selectedAdulterant?.name} in {selectedFood?.name}
            </h2>
        </div>
        <button 
          onClick={onToggleFavorite}
          className={`p-3 rounded-full transition-all duration-300 shadow-sm ${isFavorite ? 'bg-red-50 text-red-500 hover:bg-red-100' : 'bg-white text-slate-300 hover:text-red-400 hover:bg-red-50'}`}
          aria-label={isFavorite ? "Remove from favorites" : "Add to favorites"}
        >
          <Heart size={24} className={isFavorite ? 'fill-red-500' : ''} />
        </button>
      </div>

      <div className="space-y-6">
          <section className="bg-white p-5 rounded-xl shadow-sm border border-slate-100">
              <div className="flex items-center gap-2 mb-3 text-primary-700 font-bold uppercase text-xs tracking-wider">
                  <CheckCircle2 size={16} /> Aim / Object
              </div>
              <p className="text-slate-700">{activeTest.aim}</p>
          </section>

           <section className="bg-white p-5 rounded-xl shadow-sm border border-slate-100">
              <div className="flex items-center gap-2 mb-3 text-science-blue font-bold uppercase text-xs tracking-wider">
                  <Beaker size={16} /> Materials Required
              </div>
              <ul className="list-disc list-inside space-y-1 text-slate-700 marker:text-science-blue">
                  {activeTest.materials.map((m, i) => <li key={i}>{m}</li>)}
              </ul>
          </section>

          <section className="bg-white p-5 rounded-xl shadow-sm border border-slate-100">
              <div className="flex items-center gap-2 mb-3 text-purple-600 font-bold uppercase text-xs tracking-wider">
                  <BookOpen size={16} /> Procedure
              </div>
              <ol className="list-decimal list-inside space-y-3 text-slate-700 marker:font-bold marker:text-slate-400">
                  {activeTest.procedure.map((p, i) => <li key={i} className="pl-1"><span className="pl-2">{p}</span></li>)}
              </ol>
          </section>

           <section className="bg-blue-50 p-5 rounded-xl border border-blue-100">
              <div className="flex items-center gap-2 mb-3 text-blue-700 font-bold uppercase text-xs tracking-wider">
                  <Eye size={16} /> Observation
              </div>
              <p className="text-slate-800 font-medium">{activeTest.observation}</p>
          </section>

          <section className="bg-green-50 p-5 rounded-xl border border-green-100">
              <div className="flex items-center gap-2 mb-3 text-green-700 font-bold uppercase text-xs tracking-wider">
                  <CheckCircle2 size={16} /> Conclusion
              </div>
              <p className="text-slate-800 font-medium">{activeTest.conclusion}</p>
          </section>

          <section className="bg-amber-50 p-5 rounded-xl border border-amber-100">
              <div className="flex items-center gap-2 mb-3 text-amber-700 font-bold uppercase text-xs tracking-wider">
                  <ShieldAlert size={16} /> Precautions
              </div>
              <ul className="list-disc list-inside space-y-1 text-slate-800 text-sm marker:text-amber-500">
                  {activeTest.precautions.map((p, i) => <li key={i}>{p}</li>)}
              </ul>
          </section>

          <div className="flex flex-col sm:flex-row gap-3 pt-4 border-t border-slate-200">
             <Button 
                onClick={handleShare} 
                variant="outline" 
                className="flex-1 flex items-center justify-center gap-2"
             >
                <Share2 size={18} /> Share
             </Button>
             <Button 
                onClick={handleDownloadPDF} 
                className="flex-1 flex items-center justify-center gap-2"
             >
                <Download size={18} /> PDF
             </Button>
          </div>
      </div>
    </div>
  );
};
